-- ----------------------------------------------------------------------------
-- Put here INSERT statements for inserting data required by the application
-- in the "pa-project" database.
-------------------------------------------------------------------------------

INSERT INTO Lesion (lesionName, description, medication, lesionType, version) VALUES ('Contusion','Se producen por un golpe en el músculo y pueden provocar inflamación, dolor y hematomas.', 'Resfriado local y reposo.', 1, 0);
INSERT INTO Lesion (lesionName, description, medication, lesionType, version) VALUES ('Calambre','En este caso, la contracción brusca del músculo se mantiene en el tiempo, provocando dolor y limitando el movimiento.', 'Analgésico, estiramiento y masaje.', 1, 0);
INSERT INTO Lesion (lesionName, description, medication, lesionType, version) VALUES ('Distension','También se llama hiperextensión o alargamiento muscular. Se genera cuando el músculo se estira más de lo que puede cubrir. Provoca un dolor difuso que perdura en el tiempo. ', 'Analgésico, reposo y hielo en la zona.', 1, 0);
INSERT INTO Lesion (lesionName, description, medication, lesionType, version) VALUES ('Desgarro fibrilar o muscular','Una o más fibras de tejido muscular se rompen y su gravedad depende de la extensión de la lesión y su duración. El dolor es agudo y muy localizado, aunque los más severos provocan una inmovilidad inmediata del músculo.', 'Aplicación de frío en la primera fase, masaje, arcilla roja y descanso mínimo 15 días.', 1, 0);
INSERT INTO Lesion (lesionName, description, medication, lesionType, version) VALUES ('Desgarro muscular completo','El músculo se rompe por completo. El dolor es intenso y se siente la incapacidad para mover el músculo, provocando inmovilidad. ', 'El descanso es la mejor manera de recuperarse de un desgarro muscular. Además, al sufrir el desgarro, el paciente debe aplicar frío en la zona afectada (hielo o una compresa fría, durante 10 o 15 minutos). Luego puede colocar un vendaje de compresión alrededor del músculo durante 20 minutos. Pasado este tiempo, debes retirarlo durante cinco minutos y luego volver a colocarlo. Después del tercer o cuarto día, también se puede aplicar termoterapia para aumentar el metabolismo del músculo afectado.', 1, 0);

INSERT INTO Lesion (lesionName, description, medication, lesionType, version) VALUES ('Entesitis','Se caracteriza por la inflamación de las uniones de los tendones al hueso debido a microdesgarros fibrilares causados por sobrecarga. En un alto porcentaje de casos se trata de una lesión recurrente. ', 'Resto de la región lesionada y uso de medicamentos con propiedades antiinflamatorias, como aspirina e ibuprofeno, para aliviar el dolor. También se pueden realizar ejercicios de estiramiento suave, bajo la guía del fisioterapeuta o traumatólogo, con el objetivo de reducir un poco la presión en la zona.', 2, 0);
INSERT INTO Lesion (lesionName, description, medication, lesionType, version) VALUES ('Tendinitis','En este caso, el cuerpo del tendón generalmente está inflamado, aunque también puede afectar la vaina (tenosinovitis) o el peritendón (peritendinitis).', 'Para aliviar el dolor y reducir la inflamación. Por lo general, se medica con medicamentos como analgésicos, corticosteroides o plasma rico en plaquetas. Además de fisioterapia para estirar y fortalecer el músculo y tendón afectado.', 2, 0);
INSERT INTO Lesion (lesionName, description, medication, lesionType, version) VALUES ('Rotura parcial','Suele presentarse especialmente en los tendones más largos y se caracteriza por la rotura de algunas fibras.', 'Mantenga el tendón en reposo con muletas. Aplica hielo en el área. Toma analgésicos de venta libre. Mantener el tobillo en reposo durante las primeras semanas, generalmente con una bota para caminar con tacones de cuña o un yeso, o con el pie flexionado hacia abajo.', 2, 0);
INSERT INTO Lesion (lesionName, description, medication, lesionType, version) VALUES ('Rotura total','El tendón está completamente roto y generalmente ocurre en atletas mayores.', 'Mantenga el tendón en reposo con muletas. Aplica hielo en el área. Toma analgésicos de venta libre. Mantener el tobillo en reposo durante las primeras semanas, generalmente con una bota para caminar con tacones de cuña o un yeso, o con el pie flexionado hacia abajo. ', 2, 0);
INSERT INTO Lesion (lesionName, description, medication, lesionType, version) VALUES ('Dislocacion','El tendón se desplaza de su posición natural al realizar determinados movimientos. Es una lesión muy rara. ', 'Descanse la articulación dislocada. No repitas la acción que provocó tu lesión y trata de evitar movimientos dolorosos, aplica hielo y calor. Toma un analgésico. Mantenga el rango de movimiento de la articulación. ', 2, 0);

INSERT INTO Lesion (lesionName, description, medication, lesionType, version) VALUES ('Articulaciones oseas','Las lesiones articulares óseas pueden ser fracturas, con rotura parcial o total del hueso, y dislocaciones, que provocan que uno de los huesos que componen la articulación se salga de su posición normal. ', 'Tratamiento de cualquier complicación grave. Alivio del dolor. Protección, Descanso, Hielo, Compresión y Elevación. Realineación (reducción) de fragmentos que están fuera de lugar. Inmovilización, generalmente con una férula o yeso. En determinadas ocasiones, la intervención quirúrgica ', 3, 0);
INSERT INTO Lesion (lesionName, description, medication, lesionType, version) VALUES ('Cartilago','Cubren el extremo del hueso y hacen que la articulación funcione correctamente, evitando la fricción entre los huesos (los meniscos son cartílagos). Entre las lesiones más frecuentes provocadas por el deporte, hay que destacar la condromolacia, que implica la alteración del cartílago generalmente como consecuencia de un traumatismo, y la osteocondritis, que es la inflamación del cartílago. ', 'El tratamiento de la condromalacia rotuliana se puede realizar con fisioterapia, con el objetivo de mejorar la posición de la rótula y la función de la rodilla, además del uso de medicamentos antiinflamatorios y analgésicos para controlar la inflamación y el dolor, que se deben prescribir. por el médico y se utiliza según las indicaciones.', 3, 0);
INSERT INTO Lesion (lesionName, description, medication, lesionType, version) VALUES ('Membrana sinovial','Es una membrana que recubre toda la articulación para protegerla y está llena de líquido sinovial. La lesión más común es la sinovitis, es decir, una irritación de la inflamación de la membrana debido a un golpe, una torsión de la articulación o una mala postura, que provoca un aumento del volumen de líquido sinovial.', 'Suele comenzar con la aplicación de frío y calor, reposo y la toma de antiinflamatorios o incluso corticoides inyectados. Generalmente incluye la toma de antiinflamatorios, en algunos casos inyecciones de corticosteroides, la aplicación de calor y frío y reposo. La electroestimulación también puede ser un buen complemento, sobre todo si se combina con la aplicación de hielo en la rodilla, ya que facilita la relajación de los músculos y ayuda a reducir tanto el dolor como la inflamación. ', 3, 0);
INSERT INTO Lesion (lesionName, description, medication, lesionType, version) VALUES ('Reumatismos no articulares','Son estructuras blandas en forma de saco que se encuentran entre los músculos, tendones, ligamentos y prominencias óseas que componen la articulación y cuya función es evitar la fricción de los huesos durante el movimiento y amortiguar la presión ejercida sobre la articulación. La lesión más común es la bursitis, es decir, una inflamación de la bursa, que puede volverse crónica después de sucesivos episodios. Puede ser causado por hematomas, movimientos repetitivos y presión continua sobre él.', 'Aplicar hielo en la articulación afectada tres o cuatro veces al día durante los primeros días. Compresión articular. No se acueste poniendo peso sobre la articulación afectada. Tomando antiinflamatorios. Evite el sobreesfuerzo y, si es posible, el uso de la articulación.', 3, 0);

INSERT INTO Lesion (lesionName, description, medication, lesionType, version) VALUES ('Hipercifosis','Es un aumento de la curvatura de la zona dorsal.', 'Medicamentos. Es común el tratamiento de la osteoporosis asociada con la hipercifosis con fármacos antirresortivos o para la formación de huesos. Cirugía. Aparatos ortopédicos y vendajes funcionales: se han utilizado corsés y otras ortesis espinales para tratar de reducir la curva cifótica. Ejercicio.', 4, 0);
INSERT INTO Lesion (lesionName, description, medication, lesionType, version) VALUES ('Hiperlordosis','En este caso, aumenta la curvatura de la zona lumbar de la columna.', 'Sesiones de fisioterapia y con la práctica de ejercicios físicos como natación o Pilates. En fisioterapia se deben realizar diversos ejercicios que fortalezcan los músculos que se encuentran debilitados, específicamente los del abdomen, así como el estiramiento de los músculos que se encuentran atrofiados, estirando la columna. ', 4, 0);



INSERT INTO Stretching (stretchingName, description, stretchingType, version) VALUES ('Estiramiento de isquiotibiales',' 1) Siéntese en el suelo con una pierna estirada y la otra doblada con el pie lo más cerca posible del pubis.  2) Flexiona el tronco intentando tocar el pie con ambas manos.', 1, 0);
INSERT INTO Stretching (stretchingName, description, stretchingType, version) VALUES ('Estiramiento de glúteos',' 1) Acuéstese de espaldas con las piernas estiradas. 2) Doble una pierna y sosteniéndola con las manos, intente llevar el pie al hombro opuesto. 3) Mantenga el estiramiento durante 15 segundos y relájese.', 2, 0);
INSERT INTO Stretching (stretchingName, description, stretchingType, version) VALUES ('Estiramiento de pantorrillas',' 1) Pararse frente a una pared con los brazos apoyados . 2) Una pierna doblada y la otra estirada hacia atrás. 3) Lleva la pelvis hacia adelante, manteniendo la espalda recta y sin levantar el talón del suelo. 4) Mantenga la posición durante unos 20 segundos.', 3, 0);
INSERT INTO Stretching (stretchingName, description, stretchingType, version) VALUES ('Estiramiento de los aductores',' 1) Sientate en eL suelo. 2) Une las plantas de los pies y sujétalas con las manos. 3) Apoye los codos en el interior de las piernas. 4) Inclina la parte superior del cuerpo hacia adelante desde las caderas.', 4, 0);
INSERT INTO Stretching (stretchingName, description, stretchingType, version) VALUES ('Estiramiento de hombros',' 1) Ponerse de pie recto. 2) Doble un brazo y colóquelo sobre el hombro opuesto 3) Empuje el codo hacia atrás con la ayuda de la otra mano. ', 5, 0);
INSERT INTO Stretching (stretchingName, description, stretchingType, version) VALUES ('Estiramiento de cuádriceps',' 1) Acuéstate de tu lado 2) Agarra un pie con la mano del mismo lado. 3) Doble la rodilla llevando el pie al glúteo', 6, 0);
INSERT INTO Stretching (stretchingName, description, stretchingType, version) VALUES ('Estiramiento de espalda',' 1) Ponerse de pie recto 2) Levante los brazos por encima de la cabeza con los dedos entrelazados y las palmas hacia arriba. 3) Empuja tus manos hacia arriba y ligeramente hacia atrás', 7, 0);

INSERT INTO Stretching (stretchingName, description, stretchingType, version) VALUES ('Estiramiento de pectorales',' 1) Entrelaza los dedos detrás de la espalda con las palmas hacia adentro. Levante ligeramente los brazos rectos desde atrás, mientras mantiene la espalda recta.', 8, 0);
INSERT INTO Stretching (stretchingName, description, stretchingType, version) VALUES ('Estiramiento de la entrepierna',' 1) Estira la parte delantera del muslo y la ingle, ayudando a mantener la pelvis en la posición correcta y minimizando el riesgo de dolor en la espalda baja. 2) Mantenga durante 30 segundos y luego cambie de pierna.', 9, 0);
INSERT INTO Stretching (stretchingName, description, stretchingType, version) VALUES ('Estiramiento de tríceps',' 1) Coger un codo por encima de la cabeza y tirar suavemente desde detrás de la cabeza, sin tensar el cuello, manteniendo la espalda recta', 10, 0);



INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Defensa de cortes','1x1 desde el mediocampo con 2 pasadores por banda. El jugador con balón comienza dribleando hacia cualquier lado para golpear a uno de los pasadores y cortar hacia una esquina. El defensor defenderá el corte. Cuando el balón llega al segundo pasador, el atacante corta en la zona, si lo recibe en 3 segundos, juega un 1x1.', 'Mejora la defensa y 1x1', 1, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Defensa 2x2','Cuatro jugadores y una pelota Pararse en las esquinas del mediocampo Comenzar en la línea de fondo Los defensores deben correr para llegar a tiempo Se creará una situación de 2x2 posteriormente.', 'Mejora el ataque y la defensa 2x2', 1, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Disparo con bloqueo directo y continuación','Dos filas de jugadores. En la fila ubicada en 6.25 tendrán todos menos la primera pelota y en el grupo de línea de fondo todos con la pelota. El jugador de atrás enviará un pase. Cuando recibe espera el bloqueo directo. El jugador que bloquea permanece abierto y recibe el balón del siguiente en la fila. El jugador que ha recibido el bloqueo sale a disparar. Los jugadores atrapan su rebote y cambian de fila.', 'Mejora el tiro con bloqueo directo', 1, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Posesion','El equipo se divide en 2 equipos. Se coloca al azar 1 "gol" más que jugadores en cada equipo. El objetivo fundamental es mantener la posesión y conseguir la mayor cantidad de tiempo posible. Ambos se conseguirán cuando se haga un pase. de cualquiera de los "objetivos" o penetra a través de ellos. Si el equipo defensor recupera el balón, pasa al ataque.', 'Mejorar la posesión y la comunicación', 1, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Disparo tras bloqueo en el poste bajo','Un grupo de 8 o 9 jugadores; un jugador (lanzador) debajo del aro, 2 a sus lados (bloqueadores) fuera de la zona, el resto con la pelota en 2 filas en 6.25 El lanzador va hacia un lado aprovecha el bloqueo del compañero para recibir un Pase de una de las filas y rematar con un tiro a canasta El bloqueador corta el área en horizontal y aprovecha el bloqueo del tercer jugador para rematar con un tiro y así sucesivamente.', 'Mejorar el tiro exterior y los bloques interiores', 1, 0);

INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Tiro por trios','Tres jugadores con 2 balones Un pasador estático que enviará pases fuertes, altos y bien dirigidos Un reboteador que debe atrapar los rebotes y pasarlos rápido y con buenos pases Un tirador sale al encuentro del delantero con un buen cambio de ritmo, da A Regate profundo al poste bajo y tiro en suspensión. Después de aterrizar equilibrado, comience con el ala y repita.', 'Mejora el tiro y la técnica de disparo', 2, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Triangulo','Los jugadores colocados en forma triangular pasan el balón. Los controles estarán orientados. Los pases se pueden hacer con una o dos manos.', 'Mejorar pases y comunicación', 2, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Pasar, atrapar, fintar y disparar.','Pase entre dos jugadores y después de un disparo a canasta, se iniciará con un lanzamiento largo del defensor.', 'Mejora Pasar, atrapar, fintar y disparar', 2, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Poste alto y poste bajo','Tres jugadores con 2 balones. Un reboteador que debe atrapar los rebotes y pasarlos rápidamente. El tirador comienza a cortar para recibir en el poste bajo, luego de disparar sube para recibir en el poste alto y repite. Un pasador en el ala, que puede trabajar de otra manera. tipos de pase al poste bajo.', 'Mejora el tiro y el juego en el poste alto y en el poste bajo. También mejorar pases', 2, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Rueda de penetración y bandejas','Dividir la escuadra en 2 filas a cada lado de la zona Los jugadores en la fila con el balón hacen penetraciones laterales a la canasta terminando con una bandeja. Los jugadores en la fila opuesta recogen el rebote. Las filas se intercambian. Realizar el ejercicio en ambos lados del campo para mejorar el manejo de ambas manos.', 'Mejorar bandejas y penetraciones', 2, 0);

INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Sal del circulo','Intenta salir por los huecos que dejan los compañeros entre las piernas, los brazos o arriba. Párese de la mano y dentro de un jugador.', 'Mejora el físico y la velocidad', 3, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Caza en equipo','2 equipos juegan para ser eliminados. Los jugadores tendrán la pelota en sus manos y no podrán dar más de 3 pasos con ella. Un jugador será eliminado cuando sea tocado con el balón. El jugador que abandone el campo delimitado también será eliminado.', 'Mejora el físico, la velocidad y la comunicación', 3, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Farlek a todo el campo','El equipo se divide en 4 grupos que se encuentran en la línea de base. El primer grupo corre a velocidad (80%) la distancia de 6.25 a 6.25 my luego camina (recuperación). relés (uno llega, el otro se va). Se realizan 6 viajes con 4 grupos Posteriormente, se reducen a 3 grupos y con la misma dinámica se realizan 4 viajes. Finalmente se hacen 2 grupos y se hacen 2 viajes .', 'Mejora el físico, la velocidad y la comunicación', 3, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Pañuelo con globo','Juego de pañuelo pero con la pelota. Cuando el entrenador diga un número, saldrá un jugador de cada equipo. Consiste en coger el balón y conducirlo sin que el otro jugador le quite el balón.', 'Mejora el físico, la velocidad y la comunicación', 3, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Quitar el babero','Todos menos uno tendrán un babero "enganchado" en la parte de atrás de los pantalones. El que no tenga el dorsal intentará quitárselo a uno de sus compañeros. El juego terminará cuando ningún jugador tenga un dorsal.', 'Mejora el físico, la velocidad y la comunicación', 3, 0);

INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Contraataque 2 vs 2','Se distribuye a los jugadores por parejas. Se trata de realizar contraataques en una situación real 2 contra 2. Si el equipo atacante consigue una canasta, pasa el balón al equipo que espera y cambia de posición con él. Si no consigue canasta, se queda a defender y el equipo que lo defendió pasa a la posición de espera (para atacar). Ve sumando los puntos que obtiene cada equipo.', 'Mejorar el manejo del balón, la velocidad, el contraataque y la comunicación', 4, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('2 contra 2 con pases externos','Dos atacantes contra 2 defensores con 2 apoyos exteriores ubicados fuera de la línea 6.25. Si los atacantes consiguen una canasta, los defensores continúan en su rol y cambian su rol con los jugadores externos. Si no consigue canasta, se queda a defender contra el jugador. equipo exterior.', 'Mejora los ataques 2x2', 4, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Contraataque de 11','Tres jugadores en el centro del campo comenzarán a atacar. Se colocarán dos jugadores en cada zona como defensores y otros 2 en cada mitad del campo. Atacan 3 por 2 y todos van al rebote. El que atrapa el rebote pasa rápidamente a uno de los que aguardan en las bandas. El que atrapó el rebote y los 2 jugadores que estaban esperando se organizan para atacar el otro ring. Los 4 que quedan divididos: 2 defienden y 2 esperan en las bandas.', 'Mejorar el manejo del balón, la velocidad, el contraataque y la comunicación', 4, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Puntuación global 1x1','Las situaciones se juegan 1 contra 1 en el medio campo con el objetivo de llegar a una determinada cantidad de puntos (7). Se puntúan todos los aspectos ofensivos y defensivos destacados; Cesta; 1, 2 o 3 puntos. Rebote; 1 pt. Robó; 1 pt. Enchufe; 1 pt. Robo y conducción al centro del campo; 1 punto .. Se trata de terminar con los puntos exactos para ganar.', 'Mejorar 1x1', 4, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('1 contra 2 y contraataque 2 contra 1','Distribuya la escuadra en grupos de 3. Un jugador inicia el contraataque con el balón desde el fondo de la cancha hacia la canasta del oponente. Después de 2 segundos los otros dos jugadores van a buscarlo y tratan de evitar que golpee la canasta. canasta o después de recuperar el balón, se inicia un contraataque 2x1 en sentido contrario e intercambiando funciones.', 'Mejora los contraataques con ventaja', 4, 0);

INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Aleros específicos: finalizaciones exteriores','El frente de la zona se divide en 3 áreas diferentes. En cada uno de ellos el delantero recibirá un pase de cada uno de los pasadores (diferentes posiciones). El objetivo será terminar el máximo número de acciones posibles en la canasta. Los pases provienen de diferentes alturas y direcciones por lo que el movimiento y la orientación del cuerpo serán necesarios para terminar de manera rápida y eficiente.', 'Mejorar las finalizaciones exteriores', 5, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Aleros específicos: finalización con oposición','El frente de la zona se divide en 3 áreas. En cada uno de ellos se colocará un delantero. El objetivo es buscar tiros rápidos desde diferentes posiciones y con oposición. Dos pasadores de distintas posiciones exteriores serán los encargados de alimentar balones a los atacantes que no podrán salir de sus zonas de lanzamiento. Un defensor puede moverse libremente para abortar la acción ofensiva. Los atacantes tienen la posibilidad de combinarse entre sí en presencia de oposición.', 'Mejora el tiro con oposición', 5, 0);

INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Coordinacion de grupo','Todo el equipo se mueve alrededor del entrenador .. El entrenador ordena diferentes movimientos emparejados con los números que está gritando .. Algunos de estos gestos y movimientos deben ser realizados por todo el grupo al mismo tiempo .. La coordinación colectiva se verá recompensada y la descoordinación será castigado ..Gestos: Chut en el aire, aplausos saltando, ir hacia el centro, ....', 'Mejorar coordinacion de grupo', 6, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Tierra, mar y aire','Tiene lugar en el vestuario. Todo el equipo sentado en círculo. El entrenador lanza el balón a las manos de los jugadores gritando: tierra, mar o aire. Rápidamente le devuelven la pelota gritando el nombre de un animal correspondiente a ese hábitat.', 'Mejorar la relación del equipo', 6, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Concentración y reacción','Los jugadores se mueven libremente por el campo y deben reaccionar rápidamente a las instrucciones del entrenador. El juego consiste en cumplir las órdenes del entrenador lo más rápido posible.', 'Mejorar concentración y reacción', 6, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Corriendo con los ojos cerrados hacia el grupo','A una distancia de 10 metros aprox. Un jugador se para frente al grupo, tiene que cerrar los ojos y correr a toda velocidad hacia los compañeros. El grupo tiene que intentar detenerlo agarrándolo con cuidado cuando llegue a su área.', 'Mejorar la confianza del grupo', 6, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Números sin "pisar"','El equipo en grupo y estático El juego consiste en decir el siguiente número sin que en ningún momento se pongan de acuerdo 2 socios. El entrenador comenzará con 1. Se deben decir tantos números como jugadores. la numeración pero las intervenciones deben ser aleatorias y espontáneas. El objetivo es completar la secuencia o ronda completa en el menor tiempo posible.', 'Coordinación de grupo y relación de equipo', 6, 0);

INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Rueda de contraataque entre 4 jugadores','4 combinaciones seguidas entre 4 jugadores alternando posiciones: el que saca (4) ocupa el lugar del que rebota y pasa (1), este el que corre y entra en la canasta (3), y este a su vez el que corre rebota.', 'Mejora el contraataque entre 4 jugadores', 7, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Banda: Cerraduras verticales y ciegas','Patada lateral en la que la base parte del poste bajo para ir a recibir el exterior La base se mueve hacia el lado opuesto para hacer un pick y rodar con el poste alto (4) El (3) realiza un bloqueo ciego al defensor de (5) y corta el área hacia el poste alto. (4) después de hacer el pick and roll realiza un bloqueo vertical al defensor de (3). Se buscan dos posibles acabados: a) Pase y acabado exterior por (3). b) Pase interior y final 1x1 de (5).', 'Mejorar cerraduras verticales y ciegas', 7, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Banda: Tiro exterior en los últimos segundos','Los 4 atacantes están en posición de caja; 2 postes altos y 2 postes bajos. El poste alto (2) corta en el lado de saque aprovechando el bloqueo del otro poste alto (5). El poste bajo del lado opuesto al saque (3) va al exterior cortando el área y recibiendo consecutivamente los bloqueos de (5) y (4). Después de recibir el balón del servidor, este jugador (3) remata con un tiro exterior.', 'Mejora el tiro exterior en los últimos segundos', 7, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Trasfondo: Orlando Magic ','Con posición inicial en cancha; (1) base y (4) en poste bajo, (5) y (2) en poste alto La base (1) bloquea al defensor desde (5) cortando en diagonal, luego de lo cual recibe el bloqueo de (4) para salir al exterior y recibir la pelota Después del saque el ala (3) se mueve hacia el lado opuesto para recibir un bloqueo desde el poste alto (2). La acción se termina con un pick and roll de (4) a (1) y dos posibilidades; a) Finalización de (1) en rodaje. b) Ve a (3) y termina.', 'Mejorar jugadas', 7, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Background: Box horizontal - vertical','Starting at box; (1) and (3) in low post, (4) and (5) in high post. Action begins with vertical block from (4) to (1). Then (4) cuts the zone horizontally and receives a block of (3) while (1) blocks the high post (5) that cuts in the direction of the basket. The service is made on (4) who combines with the point guard (1) waiting for (2) to reach the outside after blocking (5) for outside throw.', 'Improve Background: Box horizontal - vertical', 7, 0);

INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Corre con la pelota','Por ejemplo, mientras hacen un trote suave, los jugadores hacen rebotar una pelota a lo largo de la cancha. Realizar cambios de ritmo, dirección o entradas a la canasta.', 'Calentamiento', 8, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Pases','Este ejercicio se realizaría en grupos, un jugador frente a otro que puede realizar pases de forma lineal o golpeando el balón una vez contra el suelo. También hay variaciones donde se forman unos grupos y se colocan intercalados uno de un grupo y otro de otro, donde intervienen un par de balones y deben concentrarse en recibir uno de ellos del equipo al que pertenecen. Este ejercicio estimula la concentración.', 'Mejorar pases', 8, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Tiros','Aquí, en el calentamiento, los jugadores en fila lanzarían desde ciertas posiciones, como tiros libres o tiros en carrera.', 'Tiro de calentamiento', 8, 0);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType, version) VALUES ('Jugadas ensayadas','Cualquier situación de partido específica que quieras mejorar o ensayar. Cada uno de los jugadores se colocaría en una posición estratégica, simulando alguna situación futura en el juego, de esta forma practican jugadas que han ensayado a lo largo de su entrenamiento, de esta forma no solo son capaces de ejercitar su cuerpo, sino también su mente.', 'Recordar jugadas y relajarse', 8, 0);
